import { Meta, SiteFrame } from "@/components/SiteLayout";
import { useEnquiry } from "@/contexts/EnquiryContext";
import { trackIntent } from "@/lib/analytics";
import { ArrowRight, Mail, MapPin, Phone } from "lucide-react";

export default function Contact() {
  const { openEnquiry } = useEnquiry();
  return <SiteFrame><Meta title="Contact" description="Contact Umaid Craftorium in Jodhpur, India for furniture, custom development, wholesale, export, and project enquiries." /><section className="contact-hero"><div className="shell contact-hero__grid"><div><p className="eyebrow">Contact the trade desk</p><h1>Bring a clear brief.<br /><em>We’ll take it from there.</em></h1><p>Use the enquiry flow for a collection shortlist, project requirement, custom development brief, or wholesale and export question.</p><button type="button" className="button button--dark" onClick={() => { trackIntent("contact_enquiry_start", { source: "contact" }); openEnquiry(); }}>Start an enquiry <ArrowRight size={17} /></button></div><div className="contact-details-card"><div><MapPin size={18} /><p><strong>Visit or write</strong>F-54, First Phase, Behind SBI Bank, Boranada Industrial Area, Jodhpur, Rajasthan 342012, India</p></div><div><Mail size={18} /><p><strong>Email</strong><a href="mailto:info@umaidcraftorium.com" onClick={() => trackIntent("contact_email_click", { address: "info" })}>info@umaidcraftorium.com</a><a href="mailto:umaidcraftorium.01@gmail.com" onClick={() => trackIntent("contact_email_click", { address: "alternate" })}>umaidcraftorium.01@gmail.com</a></p></div><div><Phone size={18} /><p><strong>Call</strong><a href="tel:+919829088879" onClick={() => trackIntent("contact_phone_click", { line: 1 })}>+91 98290 88879</a><a href="tel:+919414131230" onClick={() => trackIntent("contact_phone_click", { line: 2 })}>+91 94141 31230</a></p></div></div></div></section><section className="contact-note section-space section-space--sand"><div className="shell"><p className="eyebrow">How to help us help you</p><h2>Share product references, approximate quantities, intended market or project type, and any customisation needs. The more context supplied, the more useful the first trade conversation can be.</h2></div></section></SiteFrame>;
}
